import { Inter } from 'next/font/google'
import './globals.css'
import AppWrapper from '@/components/AppWrapper/AppWrapper'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <AppWrapper>
      <html lang="en">
        <body className={inter.className}>
          <main className="flex min-h-screen flex-col items-center justify-between p-24 ">
            {children}
          </main>
          <ToastContainer />
        </body>
      </html>
    </AppWrapper>
  )
}
